### ISSUE TITLE
Pagination in Carrousel with multiple visible index is broken

### ISSUE THREAD

**Issue by C4ncino** [Frontendland/webcoreui#3]
### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the bug

Hello,

First of all, I want to thank the team for the fantastic work on the component library—it's been incredibly useful for my projects!

I’m using the `Carousel` component and noticed that when I set the `visibleItems` parameter, the pagination doesn't work as expected. Here's my usage:

```ts
<Carousel items={industries.length} visibleItems={3}>
  {
    industries.map(({ slug, title, smallBanner }) => (
      <IndustryCard title={title} link={slug} img={smallBanner} />
    ))
  }
</Carousel>
```

After reviewing the source code, I found that the issue lies in the implementation of the `listen` method, specifically how the next active element is calculated. The problem is that the `pageIndex` is currently computed using addition, but to account for multiple items per page, it should use multiplication to correctly determine the next page.

I hope this helps clarify the issue.

### What's the expected result?

I noticed the following code in the `/src/components/Carousel.astro` file at line 162-163:

```ts
const visibleItems = Number(carousel.dataset.visibleItems) || 0
const pageIndex = (event.page + visibleItems) - 1
```

I made the following change:

```ts
// Added another variable to track de page where you came from

// Added max Pages and max
// Set the default to 1
const visibleItems = Number(carousel.dataset.visibleItems) || 1;
const maxPages = Number(target.dataset.totalPages) || 1;
const maxIndex = carousel.children.length;

let pageIndex = 0;

// Case: first page
if (event.page === 1) pageIndex = 0;
// Case: last page;
else if (event.page === maxPages) pageIndex = maxIndex - 1;
// Case: all other
else {
    // find middle index in the page
    pageIndex = Math.round((event.page - 1) * visibleItems + visibleItems / 2) - 1;
        
    // See if last page is gt or lt event.page to select first or last element of the page
    if (visibleItems > 1) pageIndex += lastPage < event.page ? 1 : -1;
}

// update lastpage attr
lastPage = event.page;
```

This adjustment works fine for me and since I plan to use the library in an upcoming project, I would greatly appreciate it if you could review and apply this correction. I haven't checked the React and Svelte versions of the code, but I hope this suggestion can help improve those as well.

Thank you

### Link to minimal reproducible example

.

### Severity

Low (P5)

**Comment by Frontendland** [comment]
Hey @C4ncino,

Thank you for your feedback! We're glad to hear that the library has been helpful in your project!

The `Carousel` component doesn't support multiple items per slide at the moment, so we haven't covered this case in our documentation. However, we do plan to introduce this functionality through the `visibleItems` prop that you've found. Since this is important for your upcoming project, we'll prioritize adding it in our next release based on your suggestion. In the meantime, I'll keep this issue open and provide you with updates on our progress.

Thank you.

**Comment by Frontendland** [comment]
Hey @C4ncino,

This is now available in the [latest release](https://github.com/Frontendland/webcoreui/releases/tag/v0.6.1) (v0.6.1). Please update the package to use multiple items per slide with your `Carousel` component.

- Related changes: a12f0bc487699a5a75274dd410c9fcddac7c1224
- Updated documentation: https://webcoreui.dev/docs/carousel#multiple-items-per-slide

Please note that the `visibleItems` prop you used in the previous version has been renamed to `itemsPerSlide` to make the naming less ambiguous.

I'll close this issue, but please feel free to reopen if you think the issue persists.

Thank you
