### ISSUE TITLE
Stylesheet don't found

### ISSUE THREAD

**Issue by enmanuelmag** [Frontendland/webcoreui#4]
### If this issue only occurs in one browser, which browser is a problem?

Opera

### Describe the bug

I setup the library, but when I execute `npm run dev` got the error the following error:

```
  ╷
1 │ @import '../webcore.config.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
    ../../../webcoreui/scss/config.scss 1:9    @use
    ../../../webcoreui/scss/resets.scss 1:1    @import
    ../../../webcoreui/scss/index.scss 2:9     @import
    ../../../../src/layouts/Layout.astro 2:11  root stylesheet

18:48:04 [ERROR] [sass] Error: Can't find stylesheet to import.
```

I created the `webcore.config.scss` at the root of the project:

![image](https://github.com/user-attachments/assets/653a4fd9-b70c-4042-93ba-4ce0bbf9c99e)

### What's the expected result?

Run the project and use the components.

### Link to minimal reproducible example

https://stackblitz.com/~/github.com/enmanuelmag/caputti-planner

### Severity

Blocker (P1)

**Comment by Frontendland** [comment]
Hey @enmanuelmag, thank you for reporting this issue!

Please downgrade your Astro to the latest stable version (`4.16.10`), and `sass-embedded` to `1.77.5`. The new beta version you're using are depending on an updated Sass API that currently breaks importing. We'll shortly update Sass to the latest version, but we will only support `5.0` for Astro once it has a stable version release.

Let me know if that fixes your problem!

```diff
{
  "name": "caputti-planner",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.9.4",
    "@astrojs/tailwind": "^5.1.2",
-    "astro": "^5.0.0-beta.7",
+    "astro": "4.16.10",
    "tailwindcss": "^3.4.14",
    "typescript": "^5.6.3",
    "webcoreui": "^0.7.0"
  },
  "devDependencies": {
    "@tailwindcss/typography": "^0.5.15",
-    "sass-embedded": "^1.80.6"
+    "sass-embedded": "1.77.5"
  }
}
```

**Comment by enmanuelmag** [comment]
Thanks, sadly I need to use this new Astro's version, but I'll watching when webcore update the new Sass version to use it 🙌🏼

**Comment by Frontendland** [comment]
Hey @enmanuelmag, we released a new version that updates Sass to the latest version. Unfortunately, it includes some breaking changes so you'll need to update some parts of your code:

(don't forget to update webcore beforehand to the latest version with `npm i webcoreui@latest`)

1. You can update Sass to the latest version:
```diff
- "sass": "1.77.5",
+ "sass": "1.80.7",
```
2. Update your CSS configs to use the new `@use` rule (This also applies to all places where you use these imports):
```diff
- @import 'webcoreui/styles';
- @import 'webcoreui/config';

+ @use 'webcoreui/styles' as *;
+ @use 'webcoreui/config' as *;
```

3. Update your `astro.config.mjs file` with the following setting:
```diff
export default defineConfig({
    vite: {
        ssr: {
            noExternal: ['webcoreui']
        }
+       css: {
+           preprocessorOptions: {
+                scss: {
+                   api: 'modern-compiler'
+               }
+           }
+       }
    }
})
```

You can also find the updated instructions in our [changelog](https://webcoreui.dev/docs/changelog), or in our [setup](https://webcoreui.dev/docs/setup) and [Astro integration](https://webcoreui.dev/docs/astro) guides. Please let me know how it goes so we can close this issue if it's resolved.

**Comment by Frontendland** [comment]
Hey @enmanuelmag, this issue has been inactive for a while, so I'll close it. Please reopen it if you still experience this issue.
