### ISSUE TITLE
Using Toast only, I get an error on ThemeSwitcher

### ISSUE THREAD

**Issue by g012** [Frontendland/webcoreui#6]
### Describe the bug

I've added a Toast, and I get an error at this line :

```javascript
let currentTheme = localStorage.getItem("w-theme") || getCookie("w-theme") || switchers[0].dataset.primaryTheme || "";
```
Because switchers[0] is null.
I didn't plan on using ThemeSwitcher, but adding it with an empty list works around the issue.

### What's the expected result?

I should be able to use Toast alone, without ThemeSwitcher.

### Link to minimal reproducible example

https://github.com/Frontendland/webcoreui

### Severity

High (P3)

**Comment by Frontendland** [comment]
Hey @g012, thank you for reporting this!

This issue stems from how Astro handles Astro component imports from 3rd party packages, such as WebcoreUI. It bundles JavaScript code that is not referenced. Could you please try adding the following lines in your `astro.config.mjs` configuration file and let me know how it goes?

```js
experimental: {
  directRenderScript: true // Will be enabled by default in Astro 5.0
}
```

This option will be enabled by default in the next major version update. You can read more about the option [here](https://docs.astro.build/en/reference/configuration-reference/#experimentaldirectrenderscript). I'll add a safe-guard nonetheless and include it in our next release.

**Comment by g012** [comment]
Hey @Frontendland,

Thanks, it works fine for me and doesn't seem to break anything else.

Thank you for this great library!

Cheers
