### ISSUE TITLE
Modal doesn't prevent scrolling of main content

### ISSUE THREAD

**Issue by cheradenine** [Frontendland/webcoreui#8]
### Describe the bug

When displaying a Modal the content area underneath still scrolls (using touchpad on macbook)

### What's the expected result?

Content under modal should not scroll when modal is active.

Link to example is on the webcoreui site - click the modal to display it and then scroll content underneath it.

### Link to minimal reproducible example

https://webcoreui.dev/docs/modal

### Severity

Low (P5)

**Comment by Frontendland** [comment]
Hey @cheradenine, thank you for reporting this! This will be fixed by 05354a4 in our next release.
